/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-08-27 08:09:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1660976307914L));
    _jspx_dependants.put("jar:file:/C:/Java/06_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1658880554900L));
    _jspx_dependants.put("jar:file:/C:/Java/06_Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProj/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Topbar -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t        <i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t    </button>\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Topbar Search -->\r\n");
      out.write("\t    <form\r\n");
      out.write("\t        class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("\t        <div class=\"input-group\">\r\n");
      out.write("\t            <input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\"\r\n");
      out.write("\t                aria-label=\"Search\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("\t            <div class=\"input-group-append\">\r\n");
      out.write("\t                <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t                    <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Topbar Navbar -->\r\n");
      out.write("\t    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("\t        <li class=\"nav-item dropdown no-arrow d-sm-none\">\r\n");
      out.write("\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\"\r\n");
      out.write("\t                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t                <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <!-- Dropdown - Messages -->\r\n");
      out.write("\t            <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("\t                aria-labelledby=\"searchDropdown\">\r\n");
      out.write("\t                <form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("\t                    <div class=\"input-group\">\r\n");
      out.write("\t                        <input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("\t                            placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("\t                            aria-describedby=\"basic-addon2\">\r\n");
      out.write("\t                        <div class=\"input-group-append\">\r\n");
      out.write("\t                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t                                <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t                            </button>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- Nav Item - Alerts -->\r\n");
      out.write("\t        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
      out.write("\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\"\r\n");
      out.write("\t                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t                <i class=\"fas fa-bell fa-fw\"></i>\r\n");
      out.write("\t                <!-- Counter - Alerts -->\r\n");
      out.write("\t                <span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <!-- Dropdown - Alerts -->\r\n");
      out.write("\t            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t                aria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t                <h6 class=\"dropdown-header\">\r\n");
      out.write("\t                    Alerts Center\r\n");
      out.write("\t                </h6>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"mr-3\">\r\n");
      out.write("\t                        <div class=\"icon-circle bg-primary\">\r\n");
      out.write("\t                            <i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("\t                        <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"mr-3\">\r\n");
      out.write("\t                        <div class=\"icon-circle bg-success\">\r\n");
      out.write("\t                            <i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("\t                        $290.29 has been deposited into your account!\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"mr-3\">\r\n");
      out.write("\t                        <div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t                            <i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("\t                        Spending Alert: We've noticed unusually high spending for your account.\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- Nav Item - Messages -->\r\n");
      out.write("\t        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
      out.write("\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\"\r\n");
      out.write("\t                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t                <i class=\"fas fa-envelope fa-fw\"></i>\r\n");
      out.write("\t                <!-- Counter - Messages -->\r\n");
      out.write("\t                <span class=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <!-- Dropdown - Messages -->\r\n");
      out.write("\t            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t                aria-labelledby=\"messagesDropdown\">\r\n");
      out.write("\t                <h6 class=\"dropdown-header\">\r\n");
      out.write("\t                    Message Center\r\n");
      out.write("\t                </h6>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t                        <img class=\"rounded-circle\" src=\"/resources/sbadmin2/img/undraw_profile_1.svg\"\r\n");
      out.write("\t                            alt=\"...\">\r\n");
      out.write("\t                        <div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"font-weight-bold\">\r\n");
      out.write("\t                        <div class=\"text-truncate\">Hi there! I am wondering if you can help me with a\r\n");
      out.write("\t                            problem I've been having.</div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t                        <img class=\"rounded-circle\" src=\"/resources/sbadmin2/img/undraw_profile_2.svg\"\r\n");
      out.write("\t                            alt=\"...\">\r\n");
      out.write("\t                        <div class=\"status-indicator\"></div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"text-truncate\">I have the photos that you ordered last month, how\r\n");
      out.write("\t                            would you like them sent to you?</div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t                        <img class=\"rounded-circle\" src=\"/resources/sbadmin2/img/undraw_profile_3.svg\"\r\n");
      out.write("\t                            alt=\"...\">\r\n");
      out.write("\t                        <div class=\"status-indicator bg-warning\"></div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"text-truncate\">Last month's report looks great, I am very happy with\r\n");
      out.write("\t                            the progress so far, keep up the good work!</div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t                        <img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\"\r\n");
      out.write("\t                            alt=\"...\">\r\n");
      out.write("\t                        <div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div>\r\n");
      out.write("\t                        <div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone\r\n");
      out.write("\t                            told me that people say this to all dogs, even if they aren't good...</div>\r\n");
      out.write("\t                        <div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t\r\n");
      out.write("\t        <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- 로그인이 안된 경우 -->\r\n");
      out.write("\t\t\t<!-- \r\n");
      out.write("\t\t\t\t스프링 시큐리티 표현식 : 인증 정보, 권한 정보를 다룰 수 있음. 로그인 한 사용자 정보를 확인.\r\n");
      out.write("\t\t\t\t1) 인증정보\r\n");
      out.write("\t\t\t\t - isAuthenticated() : 로그인 되었다면 true\r\n");
      out.write("\t\t\t\t - isAnonymous() : 로그인 안되었다면 true\r\n");
      out.write("\t\t\t\t - principal : 로그인 한 사용자 정보(UserDetails 인터페이스를 구현한 클래스의 객체)\r\n");
      out.write("\t\t\t\t   1(username, password) : N(athorities)\r\n");
      out.write("\t\t\t\t2) 권한 정보\r\n");
      out.write("\t\t\t\t - hasRole(role명) : 해당 role이 있으면 true\r\n");
      out.write("\t\t\t\t - hasAnyrole(role명1, role명2) : 여러 role 중 하나라도 해당하는가?\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t<a class=\"mr-2 d-none d-lg-inline text-gray-600 small\" href=\"/member/loginMember\" style=\"margin-top: 15%;\">로그인</a> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 로그인이 된 경우 시작 -->\r\n");
      out.write("\t\t\t<!-- 로그인 성공 -> session.setAttribute(\"sessionId\", pmemberVO); -->\r\n");
      out.write("\t\t\t<!-- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessioScope.sessionId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" => PmemberVO pmemberVO 객체 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- \r\n");
      out.write("\t\t\t\tisAuthenticated() : 인증된 사용자면 true(로그인 했을 경우)\r\n");
      out.write("\t\t\t\tisAnonymous() : 익명의 사용자의 경우 treu(로그인 안했을 경우)\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- End of Topbar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/tiles/header.jsp(193,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t<li class=\"nav-item dropdown no-arrow\">\r\n");
        out.write("                  <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
        out.write("                      <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">로그인 | 회원가입</span>\r\n");
        out.write("                      <img class=\"img-profile rounded-circle\" src=\"/resources/sbadmin2/img/undraw_profile.svg\">\r\n");
        out.write("                  </a>\r\n");
        out.write("\t            <!-- Dropdown - User Information -->\r\n");
        out.write("\t            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
        out.write("\t                aria-labelledby=\"userDropdown\">\r\n");
        out.write("\t                <a class=\"dropdown-item\" href=\"/product/products\">\r\n");
        out.write("\t                    <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t                    \t로그인\r\n");
        out.write("\t                </a>\r\n");
        out.write("\t                <a class=\"dropdown-item\" href=\"/member/addMember\">\r\n");
        out.write("\t                    <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t                    \t회원가입\r\n");
        out.write("\t                </a>\r\n");
        out.write("\t            </div>\t\t\t\r\n");
        out.write("                </li>\r\n");
        out.write("\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/tiles/header.jsp(222,3) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t        <!-- Nav Item - User Information -->\r\n");
        out.write("\t\t        <li class=\"nav-item dropdown no-arrow\">\r\n");
        out.write("\t\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\r\n");
        out.write("\t\t                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
        out.write("\t\t                <!-- (달러){ sessionScope.sessionId.name }님 -->\r\n");
        out.write("\t\t\t\t\t\t<!-- \r\n");
        out.write("\t\t\t\t\t\t\tprincipal 객체 : 로그인된 사용자의 사용자 정보를 담고 있는 객체\r\n");
        out.write("\t\t\t\t\t\t -->\r\n");
        out.write("\t\t                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">\r\n");
        out.write("\t\t                \t");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write('(');
        if (_jspx_meth_sec_005fauthentication_005f1(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write(")님\r\n");
        out.write("\t\t                </span>\r\n");
        out.write("\t\t                <img class=\"img-profile rounded-circle\"\r\n");
        out.write("\t\t                    src=\"/resources/sbadmin2/img/undraw_profile.svg\">\r\n");
        out.write("\t\t            </a>\r\n");
        out.write("\t\t            <!-- Dropdown - User Information -->\r\n");
        out.write("\t\t            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
        out.write("\t\t                aria-labelledby=\"userDropdown\">\r\n");
        out.write("\t\t                <a class=\"dropdown-item\" href=\"/member/detailMember?id=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.sessionId.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t\t                    <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t                    Profile\r\n");
        out.write("\t\t                </a>\r\n");
        out.write("\t\t                <a class=\"dropdown-item\" href=\"#\">\r\n");
        out.write("\t\t                    <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t                    Settings\r\n");
        out.write("\t\t                </a>\r\n");
        out.write("\t\t                <a class=\"dropdown-item\" href=\"#\">\r\n");
        out.write("\t\t                    <i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t                    Activity Log\r\n");
        out.write("\t\t                </a>\r\n");
        out.write("\t\t                <div class=\"dropdown-divider\"></div>\r\n");
        out.write("\t\t                <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\r\n");
        out.write("\t\t                    <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
        out.write("\t\t                    Logout\r\n");
        out.write("\t\t                </a>\r\n");
        out.write("\t\t            </div>\r\n");
        out.write("\t\t        </li>\r\n");
        out.write("\r\n");
        out.write("\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(232,19) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.memVO.userName");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(232,77) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.username");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }
}
